version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - smarthome-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d smarthome" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  temperature-api:
    image: nginx:stable-alpine
    container_name: temperature-app
    volumes:
      - ./temperature-api:/var/www/app:ro
      - ./temperature-api/dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - smarthome-network
    expose:
      - 8081
    restart: unless-stopped
    tty: true
    links:
      - fpm

  fpm:
    image: php:8.1-fpm
    container_name: php-fpm
    volumes:
      - ./temperature-api:/var/www/app
    networks:
      - smarthome-network
    expose:
      - 9000
    working_dir: /var/www/app
    restart: unless-stopped
    tty: true

  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/smarthome
      - TEMPERATURE_API_URL=http://temperature-api:8081
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - smarthome-network

volumes:
  postgres_data:

networks:
  smarthome-network:
    driver: bridge